language: php

php: 7.1

dist: trusty

cache:
  directories:
    - $HOME/.composer/cache/files

sudo: false

before_script:
# Init php
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - export PATH=~/.composer/vendor/bin:$PATH

# Install composer dependencies
  - composer validate
  - composer install
  - composer global require squizlabs/php_codesniffer:^3 --prefer-dist --no-interaction --no-progress --no-suggest -o

script:
  - vendor/bin/phpunit --color tests
  - composer run-script lint
